services:
  redis:
    image: redis:7.0
    container_name: redis_backend
    restart: always
    ports:
      - '6379:6379'
  postgres:
    image: postgres:15.2
    container_name: postgres_backend
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
