version: '3.9'

services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    depends_on:
      - redis
      - postgres
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules

  socket-client:
    build:
      context: .
      args:
        NODE_ENV: production
    command: node dist/utils/socketClient.js
    depends_on:
      - backend
    env_file:
      - .env.production

  redis:
    image: redis:7.0
    container_name: redis_backend
    restart: always
    ports:
      - '6379:6379'

  postgres:
    image: postgres:15.2
    container_name: postgres_backend
    restart: always
    env_file:
      - .env.production
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
