services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://Admin:Admin@localhost:5433/expressBooker?schema=public
      REDIS_URL: redis://redis_backend:6379
      JWT_SECRET: e4b6c8f3a1d24b5e8f7c9d6a2b3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
